name: Update parry84.github.io

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NodeJS setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build and Deploy
        uses: enriikke/gatsby-gh-pages-action@v2.2.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
